CREATE TABLE T_OWNER(
    ID BIGINT NOT NULL,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255)
);            
ALTER TABLE T_OWNER ADD CONSTRAINT CONSTRAINT_1 PRIMARY KEY(ID);

CREATE TABLE T_PET(
    ID BIGINT NOT NULL,
    NAME VARCHAR(255),
    BIRTH_DATE DATE,
    OWNER_ID BIGINT
);            
ALTER TABLE T_PET ADD CONSTRAINT CONSTRAINT_2 PRIMARY KEY(ID);

ALTER TABLE T_PET ADD  CONSTRAINT CONSTRAINT_3 FOREIGN KEY(OWNER_ID)  REFERENCES T_OWNER(ID);

